add dependency on gencfg so that it is built before this target
Otherwise this target cannot compile. 

CMakeFiles/velocity_smoother_nodelet.dir/src/velocity_smoother_nodelet.cpp.o -c /tmp/buildd/ros-hydro-yocs-velocity-smoother-0.4.0-0precise-20130922-0627/src/velocity_smoother_nodelet.cpp
/tmp/buildd/ros-hydro-yocs-velocity-smoother-0.4.0-0precise-20130922-0627/src/velocity_smoother_nodelet.cpp:18:49: fatal error: yocs_velocity_smoother/paramsConfig.h: No such file or directory
compilation terminated.